### ISSUE TITLE
Audio File download

### ISSUE THREAD

**Issue by LordKayBanks** [HerbertHe/edge-tts-server#1]
GET | /tts | text, voice(required) | Convert text to speech
I'm running it using Docker and I'm hitting the API from the command line. My question is,  how do I download the generated Audio file/files?

Secondly, what does this endpoint do? GET | /clean | secret(required) | Clean the exised mp3 files
what is the secret and how do we set it?

**Comment by HerbertHe** [comment]
1. The project has a frontend page, so you can save the file to local by clicking the third button.
2. The secret is for validating the right to clean the existed mp3 files. You can set secret by setting the environment variable `CLEAN_SECRET` before you run the container.

About the source code, you can visit here:

https://github.com/HerbertHe/edge-tts-server/blob/main/src/index.ts#L94

**Comment by LordKayBanks** [comment]
Thank you i got it sorted.
I didnt get the notification on time
