### ISSUE TITLE
About the returned audio format!

### ISSUE THREAD

**Issue by kisccc888** [HerbertHe/edge-tts-server#3]
Hi! Hello! Thank you for sharing, your project is great. I have a small project and I am using your docker image. I am currently using the API call to return to my ESP32S3 module. It is currently usable, but the hardware needs to be coordinated with other codes, so I need to return the 16k PCM format. Which file do I need to modify? I installed it in the Docker environment and need to return: (RAW_16KHZ_16BIT_MONO_PCM = &quot;raw-16khz-16bit-mono-pcm&quot;,). Thank you very much for your answer, thank you!

**Comment by HerbertHe** [comment]
@kisccc888 Maybe you need to issue at https://github.com/rany2/edge-tts, the project is based on this repo
